version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: library_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SUPABASE_URL: https://pjtmy8ogjqjqjqjqjqjq.supabase.co
      SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdG15OG9nanFqcWpxanFqcWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzI4MDAsImV4cCI6MjA1MjU0ODgwMH0.example-key
      SUPABASE_JWT_SECRET: your-supabase-jwt-secret
      PORT: 8080
      GIN_MODE: release
    networks:
      - library-network
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://api:8080
      NEXT_PUBLIC_SUPABASE_URL: https://pjtmy8ogjqjqjqjqjqjq.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqdG15OG9nanFqcWpxanFqcWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NzI4MDAsImV4cCI6MjA1MjU0ODgwMH0.example-key
    networks:
      - library-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  library-network:
    driver: bridge
